title: "Luc√≠a Garbayo Bugeda"
description: "Un poco de mi"
theme: jekyll-theme-minimal

nav:
  - title: "Inicio"
    url: "/"
  - title: "CV"
    url: "/cv/"
  - title: "Blog Personal"
    url: "/blog-personal/"
